{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "96dae16c-667c-43e6-9033-fd96725b7973",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q1. What is an Exception in python? Write the difference etween Exceptions and syntax errors"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5aab84ca-920e-4a5e-85e6-0268b1cf9d4f",
   "metadata": {},
   "outputs": [],
   "source": [
    "Exception:\n",
    "    for manage the unexpected error\n",
    "    \n",
    "difference etween Exceptions and syntax error:\n",
    "    exception:\n",
    "        An Exception is an event that occurs during the program execution and disrupts the normal flow of the program's execution\n",
    "    syntax error:\n",
    "         Errors mostly happen at compile-time like syntax error; however it can happen at runtime as well. Whereas an Exception occurs at runtime\n",
    "        \n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9019fa87-31bf-4bcc-88e8-94a0524a9bdf",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q2. What happens when an exception is not handled? Explain with an example"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0fa98baa-9134-44e3-9c9f-356e3e39da01",
   "metadata": {},
   "outputs": [],
   "source": [
    "when exception is not handle then program will terminate(stop) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4a6d1efb-40a9-4f2e-9e44-2c4019ae6751",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "enter a number 56\n",
      "enter a number 0\n"
     ]
    },
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[2], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m a\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mint\u001b[39m(\u001b[38;5;28minput\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124menter a number\u001b[39m\u001b[38;5;124m\"\u001b[39m))\n\u001b[1;32m      2\u001b[0m b\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mint\u001b[39m(\u001b[38;5;28minput\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124menter a number\u001b[39m\u001b[38;5;124m\"\u001b[39m))\n\u001b[0;32m----> 3\u001b[0m \u001b[43ma\u001b[49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[43mb\u001b[49m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhello\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "a=int(input(\"enter a number\"))\n",
    "b=int(input(\"enter a number\"))\n",
    "a/b\n",
    "print(\"hello\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bb563caa-bf72-4779-b67f-802191e31da9",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q3. Whi,h Python statements are used to catch and handle exceptions? Explain with an example"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "88981859-3de5-4e25-bb18-d6c7bf1ea37a",
   "metadata": {},
   "outputs": [],
   "source": [
    "which error is generated by the program execution "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "9f020719-27db-4423-a8e5-b831ad225973",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[Errno 2] No such file or directory: 'test3.txt'\n"
     ]
    }
   ],
   "source": [
    "import logging\n",
    "logging.basicConfig(filename=\"test.log\",level=logging.ERROR)\n",
    "try:\n",
    "    with open(\"test3.txt\",'r')as f:\n",
    "        test=f.read()\n",
    "except FileNotFoundError as e:\n",
    "    logging.error(\"file is not present\".format(e))\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c05b6096-878a-466b-842a-348cbb133ebe",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q4. Explain with an example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "0de3c645-974a-4f59-aa17-f975a765673e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. try and else\n",
    "\n",
    "\n",
    "import logging\n",
    "logging.basicConfig(filename=\"test.log\",level=logging.ERROR)\n",
    "def pwskills(file):\n",
    "    try:\n",
    "        with open(file,'r')as f:\n",
    "            test=f.read()\n",
    "    except FileNotFoundError as e:\n",
    "        logging.error(\"file is not present\".format(e))\n",
    "        print(e)\n",
    "    else:\n",
    "        logging.error(\"file is present\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "0f3db160-7b83-4984-bc28-7f9ffdb81703",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[Errno 2] No such file or directory: 'test3.txt'\n"
     ]
    }
   ],
   "source": [
    "pwskills(\"test3.txt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "ebc4a837-4a5f-451b-85c6-09259c8142b4",
   "metadata": {},
   "outputs": [],
   "source": [
    "pwskills(\"test.txt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "cfbe6e78-d72a-4f47-b7e7-7844f6f3e8e6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 2. finally\n",
    "\n",
    "import logging\n",
    "logging.basicConfig(filename=\"test.log\",level=logging.ERROR)\n",
    "def pwskills(file):\n",
    "    try:\n",
    "        with open(file,'r')as f:\n",
    "            test=f.read()\n",
    "    except FileNotFoundError as e:\n",
    "        logging.error(\"file is not present\".format(e))\n",
    "    else:\n",
    "        logging.error(\"file is present\")\n",
    "    finally:\n",
    "        logging.error(\"thanks foe enter your file name\")\n",
    "        print(\"thanks\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "b79ee7d9-5812-4e23-8003-88f37a357fd6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "thanks\n"
     ]
    }
   ],
   "source": [
    "pwskills(\"test3.txt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "7eb64fe8-969c-4a94-8f6f-d7aaffac8f44",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "thanks\n"
     ]
    }
   ],
   "source": [
    "pwskills(\"test.txt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "7209b316-a421-4805-a834-55b773d331c8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3. raise\n",
    "class validfile(Exception):\n",
    "    def __init__(self,file):\n",
    "        self.file=file"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "699167b8-e241-4744-abbd-ffa5408d2ba1",
   "metadata": {},
   "outputs": [],
   "source": [
    "import logging\n",
    "logging.basicConfig(filename=\"test.log\",level=logging.ERROR)\n",
    "def pwskills(file):\n",
    "    try:\n",
    "        with open(file,'r')as f:\n",
    "            test=f.read()\n",
    "    except FileNotFoundError as e:\n",
    "        logging.error(\"file is not present\".format(e))\n",
    "        raise validfile(\"file is not valid\")\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "9f216d8c-2a55-4d0d-ac71-70768d540709",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q5. What are Custom Exceptions in python? Why do we need Custom Exceptions? Explain with an example\n",
    "                        or\n",
    "Q6. Create custom exception class. Use this class to handle an exception."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "53200e07-3f68-491e-b72c-f32c41c17a2d",
   "metadata": {},
   "outputs": [],
   "source": [
    "custom Exception:\n",
    "    with the help of this we crerate or raise own exception\n",
    "    \n",
    "need custom exception:\n",
    "    if any setuation occur which is not setisfied to real world then we use custom exception\n",
    "       "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "dffcf42d-2210-4024-8c57-72763308848e",
   "metadata": {},
   "outputs": [],
   "source": [
    "class validateage(Exception):\n",
    "    \n",
    "    def __init__(self,msg):\n",
    "        self.msg=msg"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "da63fc1f-1b81-4359-bc72-9705b73c242d",
   "metadata": {},
   "outputs": [],
   "source": [
    "def validateage(age):\n",
    "    if age<0:\n",
    "        raise validateage(\"entered age is -ive\")\n",
    "    elif age>200:\n",
    "        raise validateage(\"entered age is vary high\")\n",
    "    else:\n",
    "        print(\"age is valid\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "d9beddd3-229f-4ac0-924f-16fe127fb993",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "enter your age 89\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "age is valid\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    age=int(input(\"enter your age\"))    \n",
    "    validateage(age)\n",
    "except validateage as e:\n",
    "    print(e)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
